"""
Phase 3: Human-Readable Report Generator (PDF)

Input:
- phase2_output.json

Output:
- analysis_report.pdf

Purpose:
Convert structured reasoning output into a clear,
analyst-grade, human-readable PDF report.
"""

import json
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


def load_phase2_output(path):
    with open(path, "r") as f:
        return json.load(f)


def generate_pdf_report(data, output_path="analysis_report.pdf"):
    styles = getSampleStyleSheet()
    story = []

    package = data["package"]
    analysis = data["analysis"]

    def add_title(text):
        story.append(Paragraph(f"<b>{text}</b>", styles["Title"]))
        story.append(Spacer(1, 14))

    def add_heading(text):
        story.append(Spacer(1, 12))
        story.append(Paragraph(f"<b>{text}</b>", styles["Heading2"]))
        story.append(Spacer(1, 8))

    def add_body(text):
        story.append(Paragraph(text, styles["BodyText"]))
        story.append(Spacer(1, 6))

    # ---- Report Content ----

    add_title("ReDroid-AI Static Analysis Report")
    add_body(f"<b>Package:</b> {package}")
    add_body("<b>Analysis Type:</b> Static, AI-assisted reasoning")
    add_body("<b>Generated by:</b> ReDroid-AI Phase 3")

    # Section 1: Application Overview
    add_heading("1. Application Overview")
    add_body(
        "Based on static analysis, the application exhibits behavior consistent "
        "with its declared functionality. No indicators of overtly malicious "
        "intent were observed within the analyzed scope."
    )
    add_body("<i>Confidence: Low (static analysis only; no runtime execution)</i>")

    # Section 2: Observed Static Behaviors
    add_heading("2. Observed Static Behaviors")
    for item in analysis["rule_based_analysis"]:
        add_body(f"- {item}")
    add_body(
        "<i>Confidence: Medium (derived from manifest inspection and code analysis)</i>"
    )

    # Section 3: AI-Assisted Behavioral Interpretation
    add_heading("3. AI-Assisted Behavioral Interpretation")
    for item in analysis["ai_reasoning"]["key_behaviors"]:
        add_body(f"- {item}")
    add_body(
        "<i>Confidence: Low (AI-assisted interpretation based on limited static signals)</i>"
    )

    # Section 4: Analyst Focus Areas
    add_heading("4. Analyst Focus Areas")
    for item in analysis["ai_reasoning"]["focus_areas"]:
        add_body(f"- {item}")

    # Section 5: Scope, Assumptions, and Limitations
    add_heading("5. Scope, Assumptions, and Limitations")
    add_body(
        analysis["ai_reasoning"]["limitations"]
        + " This analysis does not include dynamic execution, runtime behavior, "
          "or environmental interaction. All findings should be validated by a "
          "human analyst."
    )

    # ---- Build PDF ----
    doc = SimpleDocTemplate(output_path, pagesize=A4)
    doc.build(story)


def main():
    data = load_phase2_output("phase2_output.json")
    generate_pdf_report(data)
    print("[+] Phase 3 report written to analysis_report.pdf")


if __name__ == "__main__":
    main()
